### ISSUE TITLE
CurrPorts Question

### ISSUE THREAD

**Issue by tachyon99dwa15** [susanBuck/dwa15-spring2019#43] opened 2019-04-11 12:57 UTC
Hi Guys,

Long story short. My desktop crashed. It's in the computer shop and the guy still hasn't found a fix for it. So I have to reinstall everything on my laptop. argh! Anyhow. I finally figured how to reinstall composer and redirect it to the right version of php. Yay.

Then I when I tried to start XAMPP. it doesn't because the port is block. I downloaded currPort as suggested by the Professor Susan Buck. It shows that Port 80 is being used. I can't kill it because apparently it has a "Remote Host Name" of an old employer. They gave me the laptop. But does this mean everything I do is logged back to the old employer? I tried to close and kill the proces and run currPort as an Administrator. No luck.

I feel seriously behind. I've been catching up with the lectures and trying to do Project 3 then my desktop crashed. Do any of you guys know how to reclaim this and block the "Remote HostName" of the old employer? haha. Much appreciation!

**Comment by tachyon99dwa15** [comment] 2019-04-11 13:00
![image](https://user-images.githubusercontent.com/47389889/55959155-122a1480-5c1f-11e9-8c4b-57be66017f9e.png)

**Comment by susanBuck** [comment] 2019-04-11 16:38
What if you tried to [use an alternative port](https://github.com/susanBuck/dwa15-spring2019/blob/master/servers-and-git/local-server-troubleshooting.md#using-alternative-ports)?

**Comment by tachyon99dwa15** [comment] 2019-04-12 02:01
hi @susanBuck : Thanks for the suggestions! I changed the config file(httpd.conf) in XAMPP
#Listen 80 #I commented this out
Listen 8888

Then I restarted XAMPP and I got the following error messages:

**Comment by susanBuck** [comment] 2019-04-12 22:22
To get `http://foobooks.loc:8888` working, make sure your VirtualHost block for that domain specifies the correct port; in the notes I show the example using the default port (`80`) so you'll want to update that to `8888`:

```
<VirtualHost *:80>
    ServerName foobooks.loc
    DocumentRoot C:/xampp/htdocs/foobooks
    <Directory C:/xampp/htdocs/foobooks>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
    </Directory>
</VirtualHost>
```

**Comment by liataun** [comment] 2019-04-14 01:28
I had a similar issue where System process with PID 4 was using Port 80. In my case only one instance of it in currPort. I disabled IIS and uninstalled all MS SQL Server versions, which seemed to work. This might not be an option in your case, but I thought I would mention it. Susan's instructions for resolving a different port are probably easier.

**Comment by susanBuck** [comment] 2019-04-17 21:35
I believe Peter has had his original desktop repaired and I don't think this is an issue anymore, so I'm closing this thread out. Feel free to open a new thread if the issue is still pending!

**Closed by susanBuck** 2019-04-17 21:35 UTC
